spring:
  datasource:
    url: jdbc:h2:file:./data/campuspool
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jackson:
    serialization:
      fail-on-empty-beans: false

  web:
    locale: ko_KR
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: smtp.gmail.com
    port: 587
    username: wkddpfla3@gmail.com
    password: 

server:
  port: 8080
  address: 0.0.0.0

jwt:
  secret: your_jwt_secret_key
  expiration: 86400000  # 24시간

logging:
  level:
    org.springframework.web: DEBUG
    com.campuspoolspring: DEBUG

